default:
  image: maven:3.8.5-openjdk-17
  cache:
    paths:
      - .m2/repository/
      - target/

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - configure
  - build
  - test
  - publish

configure:
  stage: setup
  script:
    - mkdir -p .m2
    - echo '<settings>
          <servers>
            <server>
              <id>gitlab-maven</id>
              <configuration>
                <httpHeaders>
                  <property>
                    <name>Deploy-Token</name>
                    <value>${DEPLOY_TOKEN_VALUE}</value>
                  </property>
                </httpHeaders>
              </configuration>
            </server>
          </servers>
        </settings>' > .m2/settings.xml

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

publish:
  stage: publish
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
